name: Depoly Action

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true
      
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.0.5
      with:
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USER }}
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        SOURCE: "target/okhelper-service.jar"
        TARGET: "/home/ubuntu/workspace/okhelper/"
        
    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        # Private SSH key to register in the SSH agent
        ssh-private-key:  ${{ secrets.DEPLOY_KEY }}
        
    - name: Restart service
      run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} "cd /home/ubuntu/workspace/okhelper/ && chmod +x run.sh && ./run.sh"
